# Generated by Django 4.2.1 on 2023-07-17 16:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название книги')),
                ('image', models.ImageField(default='/media/books/default.jpg', upload_to='books/', verbose_name='Фотография книги')),
                ('author', models.CharField(default='', null=True, verbose_name='Автор')),
                ('publication_date', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990)], verbose_name='Год публикации')),
                ('description', models.TextField(max_length=1000, verbose_name='Аннотация к книге')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена')),
                ('count_in_stock', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('status', models.CharField(choices=[('В работе', 'В работе'), ('Передан в службу доставки', 'Передан в службу доставки'), ('Доставлен', 'Доставлен'), ('Отменен', 'Отменен')], default='В работе', verbose_name='Статус заказа')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Статус оплаты')),
                ('pay_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена доставки')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена заказа с учетом доставки')),
                ('payment_method', models.CharField(default='PayPal', verbose_name='Способ оплаты')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-order_date',),
            },
        ),
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Издательство')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrderedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('ord_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_books', to='bookshop.book')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ord_books', to='bookshop.order', verbose_name='Номер заказа')),
            ],
            options={
                'verbose_name': 'Заказанная книга',
                'verbose_name_plural': 'Заказанные книги',
                'ordering': ('-order',),
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=250, verbose_name='Адрес заказа')),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='bookshop.order', verbose_name='Номер заказа')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставок',
                'ordering': ('-order',),
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publishing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publishing_books', to='bookshop.publishing', verbose_name='Издательство'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, null=True, verbose_name='Рейтинг')),
                ('comment', models.TextField(max_length=500, verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to='bookshop.book', verbose_name='Название книги')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-date',),
                'unique_together': {('book', 'comment_author')},
            },
        ),
    ]
