# Generated by Django 4.2.1 on 2023-06-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0002_alter_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.PositiveSmallIntegerField(verbose_name='Год публикации'),
        ),
    ]
