# Generated by Django 4.2.1 on 2023-06-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0004_alter_book_author_alter_book_publishing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_author', to='bookshop.author', verbose_name='Автор'),
        ),
    ]
