# Generated by Django 4.2.1 on 2023-06-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0005_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books_author', to='bookshop.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publishing_books', to='bookshop.publishing', verbose_name='Издательство'),
        ),
        migrations.CreateModel(
            name='OrderedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('ord_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_book', to='bookshop.book')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ('-price',),
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_book',
            field=models.ManyToManyField(related_name='ord_books', to='bookshop.orderedbook', verbose_name='Заказанные книги'),
        ),
    ]
