# Generated by Django 4.2.1 on 2023-06-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0006_remove_order_total_price_alter_book_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_book',
        ),
        migrations.AddField(
            model_name='book',
            name='count_in_stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество на складе'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderedbook',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ord_books', to='bookshop.order', verbose_name='Заказанные книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'В работе'), (2, 'Передан в службу доставки'), (3, 'Доставлен'), (4, 'Отменен')], default=1, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderedbook',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=250)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.order')),
            ],
        ),
    ]
