# Generated by Django 4.2.1 on 2023-06-14 07:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0010_alter_deliveryaddress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990)], verbose_name='Год публикации'),
        ),
        migrations.AlterField(
            model_name='orderedbook',
            name='ord_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_books', to='bookshop.book'),
        ),
    ]
