# Generated by Django 4.2.1 on 2023-06-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0011_deliveryaddress_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedbook',
            name='image',
            field=models.ImageField(blank=True, upload_to='orders/', verbose_name='Фотография книги'),
        ),
        migrations.AddField(
            model_name='orderedbook',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='count_in_stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество на складе'),
        ),
    ]
