# Generated by Django 4.2.1 on 2023-06-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0012_orderedbook_image_orderedbook_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_books', to='bookshop.author', verbose_name='Автор'),
        ),
    ]
