# Generated by Django 4.2.1 on 2023-06-16 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0013_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
