# Generated by Django 4.2.1 on 2023-06-16 12:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0015_alter_deliveryaddress_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryaddress',
            options={'ordering': ('-order',), 'verbose_name': 'Адрес доставки', 'verbose_name_plural': 'Адреса доставок'},
        ),
        migrations.AlterModelOptions(
            name='orderedbook',
            options={'ordering': ('-price',), 'verbose_name': 'Заказанная книга', 'verbose_name_plural': 'Заказанные книги'},
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='address',
            field=models.TextField(max_length=250, verbose_name='Адрес заказа'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='bookshop.order', verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В работе', 'В работе'), ('Передан в службу доставки', 'Передан в службу доставки'), ('Доставлен', 'Доставлен'), ('Отменен', 'Отменен')], default=1, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена заказа с учетом доставки'),
        ),
        migrations.AlterField(
            model_name='orderedbook',
            name='image',
            field=models.ImageField(upload_to='orders/', verbose_name='Фотография книги'),
        ),
        migrations.AlterField(
            model_name='orderedbook',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='orderedbook',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ord_books', to='bookshop.order', verbose_name='Номер заказа'),
        ),
    ]
