# Generated by Django 4.2.1 on 2023-06-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0017_alter_orderedbook_options_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedbook',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orderedbook',
            name='name',
        ),
    ]
