# Generated by Django 4.2.1 on 2023-06-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0019_book_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
