# Generated by Django 4.2.1 on 2023-07-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0020_remove_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='PayPal', verbose_name='Способ оплаты'),
        ),
    ]
