# Generated by Django 4.2.1 on 2023-07-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0021_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
    ]
