# Generated by Django 4.2.1 on 2023-07-10 13:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0024_alter_book_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='author_books', to='bookshop.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='count_in_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Аннотация к книге'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='books/', verbose_name='Фотография книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990)], verbose_name='Год публикации'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='publishing_books', to='bookshop.publishing', verbose_name='Издательство'),
        ),
    ]
