# Generated by Django 4.2.1 on 2023-07-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0026_alter_book_author_alter_book_publishing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='/media/books/default.jpg', upload_to='books/', verbose_name='Фотография книги'),
        ),
    ]
