# Generated by Django 4.2.1 on 2023-07-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0027_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='', null=True, verbose_name='Автор'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
